language: r

r:
  - release
  - devel

addons:
  apt:
    packages:
      - python3
      - python3-pip

before_install:
  - pip3 install tensorflow
  - pip3 install keras

sudo: false
warnings_are_errors: true
