language: r

r:
  - release
  - devel

addons:
  apt:
    packages:
      - python3-dev
      - python3-pip

before_install:
  - python3 --version
  - pip3 install --user --upgrade -q setuptools
  - "pip3 install --user --upgrade -q https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.8.0-cp34-cp34m-linux_x86_64.whl"
  - travis_wait pip3 install --user -q keras==2.1.5

sudo: false
cache:
 - pip
 - packages
warnings_are_errors: true
